source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.2.9"

# CocoaPods dependencies
# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'xcodeproj', '>= 1.27.0'
gem 'cocoapods', '>= 1.16.2'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
# Note: xcodeproj is managed by fastlane, so we don't specify it here to avoid conflicts
gem 'concurrent-ruby', '< 1.3.4'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'

# Fastlane for iOS deployment automation
gem "fastlane", "~> 2.230"



