# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run iOS tests on simulator"
  lane :tests do
    run_tests(
      workspace: "MyReactNativeApp.xcworkspace",
      scheme: "MyReactNativeApp",
      devices: ["iPhone 17 Pro"],
      clean: true,
      code_coverage: true
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    # Optional but recommended
    tests

    # Increment build number
    increment_build_number(
      xcodeproj: "MyReactNativeApp.xcodeproj"
    )

    # Build archive for App Store
    build_app(
      workspace: "MyReactNativeApp.xcworkspace",
      scheme: "MyReactNativeApp",
      export_method: "app-store",
      clean: true
    )

    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end

